name: Deploy to AWS EC2

# develop -> main 으로 변경 예정
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Install SSH
      run: sudo apt-get install openssh-client

    - name: Remove old JAR file from EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo rm -rf /home/ubuntu/infocat

    - name: Copy files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: 'build/libs/resumerry-v2-0.0.1-SNAPSHOT.jar'
        target: '/home/ubuntu/infocat'

    - name: SSH into EC2 instance and start the application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          pid=$(lsof -t -i:8080)
          kill -9 $pid
          cd /home/ubuntu/infocat/build/libs/
          nohup java -jar -DDB_URL=${{ secrets.DB_URL }} \
                -DDB_USERNAME=${{ secrets.DB_USERNAME }} \
                -DDB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                -DMAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
                -DMAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
                -DJWT_SECRET=${{ secrets.JWT_SECRET }} \
                resumerry-v2-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &
          exit

